### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/.baggins/searchengine'

### ISSUE THREAD

**Issue by faveoled** [HariZalan/Baggins#6]
Running baggins_2.2.deb on Ubuntu 24.04:
```
$ baggins 
Traceback (most recent call last):
  File "/usr/bin/baggins", line 124, in <module>
    sEngineF=open(bagpath+"/searchengine")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/.baggins/searchengine'

```

**Comment by HariZalan** [comment]
@faveoled I have fixed the issue, prithee, clone the repository again. However, under Ubuntu 23.10, 24.04 and 24.10, the browser shall work problematically due to a security problem with AppArmor. Baggins 2.0 and 2.1 are not affected by this. See: https://gitlab.com/apparmor/apparmor/-/wikis/unprivileged_userns_restriction

This should fix the latter problem, I think:
```bash
sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
```
